language: python

sudo: true
cache: packages

python:
  - "3.5"

services:
  - docker

install:
  - ./service.sh build

before_script:
  - ./service.sh start &

script:
  - ping -o localhost
  - curl localhost

after_script:
  - ./service.sh stop

