language: python

sudo: required
cache: packages

python:
  - "3.5"

services:
  - docker

install:
  - ./service.sh build

before_script:
  - ./service.sh start &

script:
  - ping -c 4 localhost

after_script:
  - ./service.sh stop

